version: "3.8"

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npx prisma generate && npm run dev"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  prisma:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npx prisma migrate deploy"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    depends_on:
      - db

volumes:
  db_data:
